AllCops:
  TargetRubyVersion: 2.6

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/DoubleNegation:
  Enabled: false

Documentation:
  Enabled: false
